const express = require("express");
const { _getUsers } = require("../controller/users");
const { _getProducts } = require("../controller/products");
const { _getCategories } = require("../controller/categories");
const { _getContact } = require("../controller/contact");
const { _getNews } = require("../controller/news");
const { _getComment } = require("../controller/comment");
const { _getLike } = require("../controller/likee");
const { _getOrders } = require("../controller/orders");
const router = express.Router();
router.get("/users", _getUsers);
router.get("/products", _getProducts);
router.get("/categories", _getCategories);
router.get("/contact", _getContact);
router.get("/news", _getNews);
router.get("/comment", _getComment);
router.get("/like", _getLike);
router.get("/orders", _getOrders);
module.exports = router;
